// <auto-generated />
namespace MathBlog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class koko : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(koko));
        
        string IMigrationMetadata.Id
        {
            get { return "201611231505121_koko"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
